apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: environment-promotion-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/nkokkalis/gitops-cert-level-2-examples.git
    targetRevision: HEAD
    path: ./environment-promotion/envs/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: prod

  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
